/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import clases.ListaMayorista;
import clases.ListaMinorista;
import clases.ListaMostrador;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCabecera = new javax.swing.JPanel();
        lblPreciosVenta = new javax.swing.JLabel();
        panelCuerpo = new javax.swing.JPanel();
        lblCosto = new javax.swing.JLabel();
        txtCajaCosto = new javax.swing.JSpinner();
        lblVistaMostrador = new javax.swing.JLabel();
        txtCajaListaMostrador = new javax.swing.JSpinner();
        lblListaMinorista = new javax.swing.JLabel();
        txtCajaMinorista = new javax.swing.JSpinner();
        lblListaMayorista = new javax.swing.JLabel();
        txtCajaListaMayorista = new javax.swing.JSpinner();
        lblPrecioMostrador = new javax.swing.JLabel();
        txtCajaPrecioMostrador = new javax.swing.JTextField();
        lblPrecioMostrar = new javax.swing.JLabel();
        txtCajaPrecioMinorista = new javax.swing.JTextField();
        lblPrecioMayorista = new javax.swing.JLabel();
        txtCajaPrecioMayorista = new javax.swing.JTextField();
        panelBotones = new javax.swing.JPanel();
        txtCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCabecera.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblPreciosVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPreciosVenta.setText("CALCULAR PRECIOS DE VENTA");

        javax.swing.GroupLayout panelCabeceraLayout = new javax.swing.GroupLayout(panelCabecera);
        panelCabecera.setLayout(panelCabeceraLayout);
        panelCabeceraLayout.setHorizontalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lblPreciosVenta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCabeceraLayout.setVerticalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCabeceraLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(lblPreciosVenta)
                .addGap(19, 19, 19))
        );

        panelCuerpo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCosto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCosto.setText("COSTO:");

        txtCajaCosto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCajaCosto.setToolTipText("");

        lblVistaMostrador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblVistaMostrador.setText("% VISTA MOSTRADOR:");

        txtCajaListaMostrador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblListaMinorista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblListaMinorista.setText("% LISTA MINORISTA: ");

        txtCajaMinorista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblListaMayorista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblListaMayorista.setText("% LISTA MAYORISTA:");

        txtCajaListaMayorista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblPrecioMostrador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrecioMostrador.setText("PRECIO MOSTRADOR:");

        txtCajaPrecioMostrador.setEditable(false);
        txtCajaPrecioMostrador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblPrecioMostrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrecioMostrar.setText("PRECIO MINORISTA:");

        txtCajaPrecioMinorista.setEditable(false);
        txtCajaPrecioMinorista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCajaPrecioMinorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCajaPrecioMinoristaActionPerformed(evt);
            }
        });

        lblPrecioMayorista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrecioMayorista.setText("PRECIO MAYORISTA:");

        txtCajaPrecioMayorista.setEditable(false);
        txtCajaPrecioMayorista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout panelCuerpoLayout = new javax.swing.GroupLayout(panelCuerpo);
        panelCuerpo.setLayout(panelCuerpoLayout);
        panelCuerpoLayout.setHorizontalGroup(
            panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuerpoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCosto)
                    .addComponent(lblVistaMostrador)
                    .addGroup(panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblListaMinorista)
                        .addGroup(panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecioMayorista)
                            .addGroup(panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblListaMayorista)
                                .addComponent(lblPrecioMostrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPrecioMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCajaCosto, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(txtCajaListaMostrador)
                    .addComponent(txtCajaMinorista)
                    .addComponent(txtCajaListaMayorista)
                    .addComponent(txtCajaPrecioMostrador)
                    .addComponent(txtCajaPrecioMinorista)
                    .addComponent(txtCajaPrecioMayorista))
                .addGap(31, 31, 31))
        );
        panelCuerpoLayout.setVerticalGroup(
            panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuerpoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCosto)
                    .addComponent(txtCajaCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVistaMostrador)
                    .addComponent(txtCajaListaMostrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCajaMinorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblListaMinorista))
                .addGap(18, 18, 18)
                .addGroup(panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblListaMayorista)
                    .addComponent(txtCajaListaMayorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCajaPrecioMostrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecioMostrador))
                .addGap(18, 18, 18)
                .addGroup(panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioMostrar)
                    .addComponent(txtCajaPrecioMinorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioMayorista)
                    .addComponent(txtCajaPrecioMayorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtCalcular.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtCalcular.setText("CALCULAR");
        txtCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(txtCalcular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtCalcular)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCajaPrecioMinoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCajaPrecioMinoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCajaPrecioMinoristaActionPerformed

    private void txtCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalcularActionPerformed
        //*****************************************************
        //definicion de variables
        //*****************************************************
        ListaMostrador objMostrador;
        ListaMinorista objMinorista;
        ListaMayorista objMayorista;
        Double costo, porcentajeMostrador,porcentajeMinorista,porcentajeMayorista;
        Double precioMostrador, precioMinorista,precioMayorista;
        //*****************************************************
        //*****************************************************
        //creacion de objetos
        //*****************************************************
        objMostrador = new ListaMostrador();
        objMinorista = new ListaMinorista();
        objMayorista = new ListaMayorista();
        //*****************************************************
       
        try {
            //*****************************************************
            //capturar datos desde la interfaz
            //*****************************************************
            costo = Double.parseDouble(txtCajaCosto.getValue().toString());
            porcentajeMostrador = Double.parseDouble(txtCajaListaMostrador.getValue().toString());
            porcentajeMinorista = Double.parseDouble(txtCajaMinorista.getValue().toString());
            porcentajeMayorista = Double.parseDouble(txtCajaListaMayorista.getValue().toString());
            //******************************************************
           
            objMostrador.setCosto(costo);
            objMostrador.setGananciaMostrador(porcentajeMostrador);
            precioMostrador = objMostrador.calcularPrecioVenta();
            txtCajaPrecioMostrador.setText(precioMostrador.toString());
            
            objMinorista.setCosto(costo);
            objMinorista.setGananciaMinorista(porcentajeMinorista);
            precioMinorista = objMinorista.calcularPrecioVenta();
            txtCajaPrecioMinorista.setText(precioMinorista.toString());
            
            objMayorista.setCosto(costo);
            objMayorista.setGananciaMayorista(porcentajeMayorista);
            precioMayorista = objMayorista.calcularPrecioVenta();
            txtCajaPrecioMayorista.setText(precioMayorista.toString());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(panelCuerpo, "Error: Los valores deben ser numericos.");
        }
    }//GEN-LAST:event_txtCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblListaMayorista;
    private javax.swing.JLabel lblListaMinorista;
    private javax.swing.JLabel lblPrecioMayorista;
    private javax.swing.JLabel lblPrecioMostrador;
    private javax.swing.JLabel lblPrecioMostrar;
    private javax.swing.JLabel lblPreciosVenta;
    private javax.swing.JLabel lblVistaMostrador;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCabecera;
    private javax.swing.JPanel panelCuerpo;
    private javax.swing.JSpinner txtCajaCosto;
    private javax.swing.JSpinner txtCajaListaMayorista;
    private javax.swing.JSpinner txtCajaListaMostrador;
    private javax.swing.JSpinner txtCajaMinorista;
    private javax.swing.JTextField txtCajaPrecioMayorista;
    private javax.swing.JTextField txtCajaPrecioMinorista;
    private javax.swing.JTextField txtCajaPrecioMostrador;
    private javax.swing.JButton txtCalcular;
    // End of variables declaration//GEN-END:variables
}
